url: 'ws://example.com'
name: 'server'
token: 'ffffffff-ffff-ffff-ffff-ffffffffffff'
ConsoleLogForward:
  enable: false
  filter:
    enable: true
    list:
      - 'WebSocketWrite'
      - 'WebSocketRead'
      - 'WebSocketConnect'
      - 'WebSocket Reconnecting'
ChatEvent: false
PlayerLoginEvent: false
PlayerLogoutEvent: false
PlayerCommandEvent: false
RconCommandEvent: false