name: BotConnector
version: ${project.version}
main: com.github.hank9999.botconnector.BotConnectorBukkit
api-version: 1.13
authors: [ hank9999 ]
description: Connect your Minecraft server with the bot program via WebSocket
website: https://github.com/hank9999/BotConnector
